spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8001
          predicates:
            - Path=/api/auth/**
        - id: user-service
          uri: http://localhost:8002
          predicates:
            - Path=/api/users/**
        - id: approval-service
          uri: http://localhost:8003
          predicates:
            - Path=/api/approvals/**
        - id: health-service
          uri: http://localhost:8004
          predicates:
            - Path=/api/health/**

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
